spring:
  datasource:
    url: jdbc:h2:mem:bookdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    #generate-ddl: true
    hibernate:
      ddl-auto: none
    #show-sql: true

  shell:
    interactive:
      enabled: true